### ISSUE TITLE
Any 'official' test sets & results to be released?

### ISSUE THREAD

**Issue by zhyack** [keithecarlson/Zero-Shot-Style-Transfer#1]
Hi, keithecarlson,

I find your work very interesting and I'd like to follow your work to do some experiments on the released dataset. However, the results in your paper is not concerned with these data. As I want to have something to compare, I wonder if you have any plan to release your test sets of these data (better with results of MOSES and Seq2Seq), so that people can follow and cite your work. 

Sincerely~

**Comment by keithecarlson** [comment]
Thanks for your interest in this work.  Unfortunately most of the data we use in the paper is under copyright and we are not able to release it.  We make the versions which are in the public domain available here, but they do not make up the full dataset used in the paper.  We are considering creating test and training sets using only the public data and reporting results using only these separately.  If we run this experiment I will be sure to let you know.

**Comment by zhyack** [comment]
Thank you for your reply! 
I'm looking forward to that :smiley:.
